set specific encoding for all platforms
Azure/aaz-dev-tools pull request #298
Opened 2023-10-30 05:59 UTC by AllyW

For *nix os, utf8 is default system encoding which is used when python open func is working without a given encoding format.

However, windows may use local systems encoding which might be incompatible with non-ascii characters in files. 

Set encoding in file operations can avoid this error.

![image](https://github.com/Azure/aaz-dev-tools/assets/8137253/05804cc6-16a2-4b98-a889-34922c81b6a7)

2023-10-30 07:42 UTC, kairu-ms approved these changes

2023-10-30 07:46 UTC, kairu-ms requested changes
Most characters are gibberish, do we need support them? Or we can filter them out from swagger source.

2023-10-30 07:59 UTC, AllyW commented
> Most characters are gibberish, do we need support them?

CodeGen, or workspace manager in Codegen here is in charge of loading and enabling the management of related api definitions in swagger file. 

Swagger quality and cleaning can be checked and enhanced by service developer when generating codes or by codegen developer when pre-loading swaggers (if planed later), in my view.

2023-10-30 08:10 UTC, kairu-ms commented
> > Most characters are gibberish, do we need support them?
> 
> CodeGen, or workspace manager in Codegen here is in charge of loading and enabling the management of related api definitions in swagger file.
> 
> Swagger quality and cleaning can be checked and enhanced by service developer when generating codes or by codegen developer when pre-loading swaggers (if planed later), in my view.

It's better clean then when loading swaggers. Can you add this support in current PR? I think those can be added in this function https://github.com/Azure/aaz-dev-tools/blob/b8386bea21066ea745efbecf7f2df3b8b80e4040/src/aaz_dev/swagger/model/specs/_swagger_loader.py#L18-L34

2023-11-08 03:36 UTC, kairu-ms approved these changes

2023-11-08 03:36 UTC, merged